In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [99]:
df=pd.read_csv('Campaign data.csv')

In [100]:
df

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00
1,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00
2,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00
3,12/30/2019,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00
4,12/30/2019,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00
...,...,...,...,...,...,...,...
123694,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [101]:
df.shape

(123699, 7)

In [102]:
df.columns

Index(['Date', 'Data source', 'Campaign', 'Media Type', 'City', 'Metric',
       'Value'],
      dtype='object')

In [103]:
df.head()

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0
1,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.0
2,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0
3,12/30/2019,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0
4,12/30/2019,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.0

In [104]:
df.tail()

,Date,Data source,Campaign,Media Type,City,Metric,Value
123694,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [105]:
df.iloc()

In [106]:
df1=pd.DataFrame(data=df,columns=['Date'])

In [107]:
df1

              Date
0       12/30/2019
1       12/30/2019
2       12/30/2019
3       12/30/2019
4       12/30/2019
...            ...
123694   9/30/2021
123695   9/30/2021
123696   9/30/2021
123697   9/30/2021
123698   9/30/2021

[123699 rows x 1 columns]

In [108]:
df.dtypes

Date            object
Data source     object
Campaign        object
Media Type      object
City            object
Metric          object
Value          float64
dtype: object

In [109]:
df.isnull().sum()

Date           0
Data source    0
Campaign       0
Media Type     0
City           0
Metric         0
Value          0
dtype: int64

In [110]:
df

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00
1,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00
2,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00
3,12/30/2019,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00
4,12/30/2019,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00
...,...,...,...,...,...,...,...
123694,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [111]:
df.columns

Index(['Date', 'Data source', 'Campaign', 'Media Type', 'City', 'Metric',
       'Value'],
      dtype='object')

In [112]:
df.nunique()

Date             332
Data source        2
Campaign          58
Media Type         2
City             263
Metric             3
Value          43408
dtype: int64

In [113]:
df[df.duplicated()]

,Date,Data source,Campaign,Media Type,City,Metric,Value
80807,3/29/2021,Pinterest,shop at home,Display,Utica,Clicks,3.00
80858,3/29/2021,Pinterest,shop at home,Display,Utica,Clicks,3.00
80907,3/29/2021,Pinterest,shop at home,Display,Utica,Impressions,750.00
80908,3/29/2021,Pinterest,shop at home,Display,Utica,Media Cost,5.33
80909,3/29/2021,Pinterest,shop at home,Display,Utica,Clicks,3.00
...,...,...,...,...,...,...,...
122584,9/27/2021,Pinterest,shop at home,Display,Miami-Ft. Lauderdale,Media Cost,0.00
122585,9/27/2021,Pinterest,shop at home,Display,Miami-Ft. Lauderdale,Clicks,0.00
122586,9/27/2021,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Impressions,2.00
122587,9/27/2021,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Media Cost,0.00
122588,9/27/2021,Pinterest,shop at home,Display,Harlingen-Wslco-Brnsvl-Mca,Clicks,0.00

In [114]:
df.drop_duplicates(inplace=True)

In [115]:
df[df.duplicated()]

Empty DataFrame
Columns: [Date, Data source, Campaign, Media Type, City, Metric, Value]
Index: []

In [116]:
df.shape

(122629, 7)

In [117]:
df.describe()

              Value
count  1.226290e+05
mean   6.999154e+03
std    3.411575e+04
min    0.000000e+00
25%    6.340000e+00
50%    7.600000e+01
75%    1.156000e+03
max    1.627800e+06

In [118]:
df.sort_values

<bound method DataFrame.sort_values of               Date Data source               Campaign    Media Type  \
0       12/30/2019   Pinterest       Kicks campaign 2       Display
1       12/30/2019   Pinterest       Kicks campaign 2       Display
2       12/30/2019   Pinterest       Kicks campaign 2       Display
3       12/30/2019   Pinterest       Kicks campaign 2       Display
4       12/30/2019   Pinterest       Kicks campaign 2       Display
...            ...         ...                    ...           ...
123694   9/30/2021    Snapchat  Pathfinder campaign 7  Online Video
123695   9/30/2021    Snapchat  Pathfinder campaign 7  Online Video
123696   9/30/2021    Snapchat  Pathfinder campaign 7  Online Video
123697   9/30/2021    Snapchat  Pathfinder campaign 7  Online Video
123698   9/30/2021    Snapchat  Pathfinder campaign 7  Online Video

                                   City       Metric     Value
0               Colorado Springs-Pueblo  Impressions      1.00
1               Colorado Springs-Pueblo   Media Cost      0.00
2               Colorado Springs-Pueblo       Clicks      0.00
3              Sacramnto-Stkton-Modesto  Impressions      1.00
4              Sacramnto-Stkton-Modesto   Media Cost      0.00
...                                 ...          ...       ...
123694  Sacramento - Stockton - Modesto   Media Cost    136.94
123695  Sacramento - Stockton - Modesto       Clicks     81.00
123696               Dallas - Ft. Worth  Impressions  16579.00
123697               Dallas - Ft. Worth   Media Cost    297.78
123698               Dallas - Ft. Worth       Clicks    128.00

[122629 rows x 7 columns]>

In [119]:
df.sample()

,Date,Data source,Campaign,Media Type,City,Metric,Value
81603,4/5/2021,Pinterest,Armada campaign 2,Display,Houston,Impressions,9.0

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122629 entries, 0 to 123698
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Date         122629 non-null  object
 1   Data source  122629 non-null  object
 2   Campaign     122629 non-null  object
 3   Media Type   122629 non-null  object
 4   City         122629 non-null  object
 5   Metric       122629 non-null  object
 6   Value        122629 non-null  float64
dtypes: float64(1), object(6)
memory usage: 7.5+ MB

In [121]:
df.describe(include='all')

,Date,Data source,Campaign,Media Type,City,Metric,Value
count,122629,122629,122629,122629,122629,122629,1.226290e+05
unique,332,2,58,2,263,3,NaN
top,9/27/2021,Pinterest,Armada campaign 2,Online Video,New York,Impressions,NaN
freq,3813,65875,13392,99363,3483,40899,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,6.999154e+03
std,NaN,NaN,NaN,NaN,NaN,NaN,3.411575e+04
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,NaN,6.340000e+00
50%,NaN,NaN,NaN,NaN,NaN,NaN,7.600000e+01
75%,NaN,NaN,NaN,NaN,NaN,NaN,1.156000e+03
max,NaN,NaN,NaN,NaN,NaN,NaN,1.627800e+06

In [122]:
df.loc[:,'City']

0                 Colorado Springs-Pueblo
1                 Colorado Springs-Pueblo
2                 Colorado Springs-Pueblo
3                Sacramnto-Stkton-Modesto
4                Sacramnto-Stkton-Modesto
                       ...
123694    Sacramento - Stockton - Modesto
123695    Sacramento - Stockton - Modesto
123696                 Dallas - Ft. Worth
123697                 Dallas - Ft. Worth
123698                 Dallas - Ft. Worth
Name: City, Length: 122629, dtype: object

In [123]:
df.dropna(inplace=True)

In [124]:
df

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00
1,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00
2,12/30/2019,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00
3,12/30/2019,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00
4,12/30/2019,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00
...,...,...,...,...,...,...,...
123694,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94
123695,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00
123696,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00
123697,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78
123698,9/30/2021,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00

In [125]:
#nsmallest - return the first n rows ordered by columns in ascending order
#nlargest - return the first n rows ordered by columns in descending order

Find out the top 5 months in terms of impression

In [126]:
df['Date']=pd.to_datetime(df['Date'])

In [127]:
df.dtypes

Date           datetime64[ns]
Data source            object
Campaign               object
Media Type             object
City                   object
Metric                 object
Value                 float64
dtype: object

In [128]:
df.head()

,Date,Data source,Campaign,Media Type,City,Metric,Value
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.0
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.0

In [129]:
df['Day']=df['Date'].dt.day
df['Month']=df['Date'].dt.month
df['Year']=df['Date'].dt.year

In [130]:
df

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021

In [131]:
df_imp=df[df['Metric']=='Impressions']

In [132]:
df_imp

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123684,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021
123687,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021
123690,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021

In [133]:
(df_imp.groupby('Month')['Value'].sum()).sort_values(ascending=False)[:5]

Month
9     195438538.0
3     159488182.0
10    129386691.0
8     117299533.0
2      95672149.0
Name: Value, dtype: float64

In [134]:
(df.groupby(['Month','Metric','Year'])['Value'].sum()).sort_values(ascending=False).reset_index()

    Month       Metric  Year        Value
0       9  Impressions  2021  165961494.0
1      10  Impressions  2020  129386691.0
2       8  Impressions  2021  110579025.0
3       3  Impressions  2021  101719848.0
4       2  Impressions  2020   61351689.0
..    ...          ...   ...          ...
61      4   Media Cost  2020          0.0
62      5   Media Cost  2020          0.0
63      5   Media Cost  2021          0.0
64      6   Media Cost  2021          0.0
65      1       Clicks  2020          0.0

[66 rows x 4 columns]

In [135]:
large5=df.nlargest(5,'Value')

In [136]:
large5

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year
110946,2021-09-13,Pinterest,Pathfinder campaign 1,Display,Los Angeles,Impressions,1627800.0,13,9,2021
3936,2020-03-09,Pinterest,Armada campaign 2,Display,Los Angeles,Impressions,1483786.0,9,3,2020
115773,2021-09-20,Pinterest,Pathfinder campaign 1,Display,Los Angeles,Impressions,1366794.0,20,9,2021
3279,2020-03-02,Pinterest,Armada campaign 2,Display,Los Angeles,Impressions,1331403.0,2,3,2020
2703,2020-03-02,Pinterest,Armada campaign 2,Display,New York,Impressions,1323275.0,2,3,2020

In [137]:
df['Value'].nlargest(n=5)

110946    1627800.0
3936      1483786.0
115773    1366794.0
3279      1331403.0
2703      1323275.0
Name: Value, dtype: float64

In [138]:
df.groupby('Date')['Value'].nlargest(5)

Date
2019-12-30  18            5.0
            15            3.0
            6             2.0
            12            2.0
            0             1.0
                       ...
2021-09-30  123564    72080.0
            123600    55909.0
            123597    44954.0
            123576    43478.0
            123612    35335.0
Name: Value, Length: 1660, dtype: float64

In [139]:
large5=df.nlargest(5,'Value')['Metric']

In [140]:
large5

110946    Impressions
3936      Impressions
115773    Impressions
3279      Impressions
2703      Impressions
Name: Metric, dtype: object

In [141]:
df.groupby('Metric')['Value'].nlargest(5)

Metric
Clicks       3938         2879.00
             1409         2749.00
             2705         2692.00
             2630         2640.00
             3281         2634.00
Impressions  110946    1627800.00
             3936      1483786.00
             115773    1366794.00
             3279      1331403.00
             2703      1323275.00
Media Cost   35167       15365.90
             30283       15111.60
             25663       14072.47
             35170       12059.50
             30286       11975.97
Name: Value, dtype: float64

Find out the top 5 months in terms of impression

In [142]:
df_c=df[df['Metric']=='Impressions']

In [143]:
df_c

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123684,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021
123687,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021
123690,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021

In [144]:
large5=df_c.nlargest(5,'Value')['Date']

In [145]:
large5

110946   2021-09-13
3936     2020-03-09
115773   2021-09-20
3279     2020-03-02
2703     2020-03-02
Name: Date, dtype: datetime64[ns]

In [146]:
df_c['Date']=pd.to_datetime(df_c['Date'])

In [147]:
df_c

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123684,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021
123687,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021
123690,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021

In [148]:
large5=df_c.nlargest(5,'Value')['Date']

In [149]:
large5

110946   2021-09-13
3936     2020-03-09
115773   2021-09-20
3279     2020-03-02
2703     2020-03-02
Name: Date, dtype: datetime64[ns]

Which model has maximum impressions?

In [150]:
ds=pd.read_csv('Campaign datas.csv')

In [151]:
ds

                 Campaign   Message type        Model
0       Sentra campaign 2  Future Market       Sentra
1       Sentra campaign 4  Future Market       Sentra
2       Sentra campaign 3  Future Market       Sentra
3       Sentra campaign 1  Future Market       Sentra
4       Altima campaign 1  Future Market       Altima
5       Altima campaign 5  Future Market       Altima
6       Altima campaign 4  Future Market       Altima
7       Altima campaign 6  Future Market       Altima
8        Kicks campaign 6  Future Market        Kicks
9        Kicks campaign 5  Future Market        Kicks
10       Rogue campaign 1  Future Market        Rogue
11       Rogue campaign 3  Future Market        Rogue
12       Rogue pre launch  Future Market        Rogue
13       Rogue campaign 5  Future Market        Rogue
14       Rogue campaign 4  Future Market        Rogue
15  Pathfinder campaign 3    Near Market   Pathfinder
16      Armada campaign 1    Near Market       Armada
17  Pathfinder campaign 8    Near Market   Pathfinder
18  Pathfinder campaign 5    Near Market   Pathfinder
19  Pathfinder campaign 6    Near Market   Pathfinder
20  Pathfinder campaign 7    Near Market   Pathfinder
21      Altima campaign 3  Future Market       Altima
22      Altima campaign 2  Future Market       Altima
23      Altima campaign 7    Near Market       Altima
24      Altima campaign 8    Near Market       Altima
25       Rogue campaign 2  Future Market        Rogue
26       Kicks campaign 3  Future Market        Kicks
27       Kicks campaign 4  Future Market        Kicks
28  Pathfinder campaign 2    Near Market   Pathfinder
29  Pathfinder campaign 1    Near Market   Pathfinder
30  Pathfinder campaign 4    Near Market   Pathfinder
31           shop at home  Future Market  Multi-Model
32       Kicks campaign 2    Near Market        Kicks
33       Kicks campaign 1    Near Market        Kicks
34      Armada campaign 2    Near Market       Armada
35      Armada campaign 4    Near Market       Armada
36      Armada campaign 3    Near Market       Armada
37     Sentra campaign 11    Near Market       Sentra
38     Sentra campaign 14    Near Market       Sentra
39     Sentra campaign 20    Near Market       Sentra
40     Sentra campaign 21    Near Market       Sentra
41      Sentra campaign 9    Near Market       Sentra
42      Sentra campaign 7    Near Market       Sentra
43      Sentra campaign 6    Near Market       Sentra
44     Sentra campaign 12    Near Market       Sentra
45     Sentra campaign 19    Near Market       Sentra
46     Sentra campaign 18    Near Market       Sentra
47     Sentra campaign 22    Near Market       Sentra
48     Sentra campaign 23    Near Market       Sentra
49     Sentra campaign 25    Near Market       Sentra
50      Sentra campaign 5    Near Market       Sentra
51     Sentra campaign 13    Near Market       Sentra
52     Sentra campaign 15    Near Market       Sentra
53      Sentra campaign 8    Near Market       Sentra
54     Sentra campaign 10    Near Market       Sentra
55     Sentra campaign 24    Near Market       Sentra
56     Sentra campaign 16    Near Market       Sentra
57     Sentra campaign 17    Near Market       Sentra

In [152]:
df

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021

In [153]:
df_m=pd.merge(df,ds,on='Campaign')

In [154]:
df_m

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [155]:
df_m.head(3)

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.0,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0,30,12,2019,Near Market,Kicks

In [156]:
df_m.max()

Date            2021-09-30 00:00:00
Data source                Snapchat
Campaign               shop at home
Media Type             Online Video
City                     Zanesville
Metric                   Media Cost
Value                     1627800.0
Day                              31
Month                            12
Year                           2021
Message type            Near Market
Model                        Sentra
dtype: object

In [157]:
df_m[df_m['Metric'] == 'Impressions']

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019,Near Market,Kicks
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019,Near Market,Kicks
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122614,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021,Near Market,Pathfinder
122617,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021,Near Market,Pathfinder
122620,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021,Near Market,Pathfinder
122623,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021,Near Market,Pathfinder

In [158]:
(df_m.groupby('Model')['Value'].sum()).sort_values(ascending=False)[:3]

Model
Pathfinder    2.793421e+08
Armada        1.770488e+08
Rogue         1.339567e+08
Name: Value, dtype: float64

Find out the top 3 campaigns in terms of impressions for every message type

In [159]:
df_m

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [160]:
(df_m.groupby(['Message type','Campaign'])['Value'].sum()).sort_values(ascending=False).reset_index()

     Message type               Campaign         Value
0     Near Market      Armada campaign 2  1.197572e+08
1     Near Market  Pathfinder campaign 2  1.160629e+08
2     Near Market  Pathfinder campaign 6  5.285515e+07
3     Near Market  Pathfinder campaign 1  4.921421e+07
4   Future Market      Altima campaign 3  4.584127e+07
5     Near Market      Armada campaign 4  3.782937e+07
6   Future Market      Altima campaign 1  3.650185e+07
7   Future Market       Kicks campaign 4  3.387167e+07
8   Future Market       Rogue campaign 5  3.379682e+07
9   Future Market       Kicks campaign 6  3.353479e+07
10  Future Market       Rogue campaign 4  3.320477e+07
11  Future Market       Kicks campaign 3  2.740015e+07
12  Future Market       Rogue campaign 2  2.590745e+07
13  Future Market       Rogue campaign 1  1.921213e+07
14    Near Market  Pathfinder campaign 5  1.771970e+07
15    Near Market      Armada campaign 3  1.765449e+07
16    Near Market  Pathfinder campaign 7  1.714928e+07
17  Future Market       Rogue pre launch  1.700952e+07
18    Near Market  Pathfinder campaign 8  1.658158e+07
19    Near Market     Sentra campaign 11  7.898963e+06
20  Future Market      Altima campaign 2  7.278116e+06
21    Near Market     Sentra campaign 14  7.185905e+06
22    Near Market      Altima campaign 8  6.222003e+06
23    Near Market  Pathfinder campaign 4  5.687674e+06
24  Future Market      Sentra campaign 3  5.592684e+06
25  Future Market           shop at home  4.984773e+06
26  Future Market       Rogue campaign 3  4.826010e+06
27    Near Market  Pathfinder campaign 3  4.071607e+06
28    Near Market      Sentra campaign 7  4.034150e+06
29    Near Market     Sentra campaign 21  3.159277e+06
30  Future Market      Sentra campaign 1  3.144530e+06
31    Near Market     Sentra campaign 12  3.140968e+06
32    Near Market     Sentra campaign 20  3.111988e+06
33    Near Market      Sentra campaign 6  2.999087e+06
34    Near Market     Sentra campaign 22  2.954462e+06
35    Near Market     Sentra campaign 18  2.524658e+06
36    Near Market      Sentra campaign 9  2.403540e+06
37    Near Market     Sentra campaign 15  2.151847e+06
38    Near Market      Altima campaign 7  2.063712e+06
39    Near Market     Sentra campaign 19  2.029303e+06
40  Future Market       Kicks campaign 5  2.022436e+06
41    Near Market     Sentra campaign 23  1.894045e+06
42    Near Market      Armada campaign 1  1.807682e+06
43    Near Market     Sentra campaign 25  1.725227e+06
44    Near Market     Sentra campaign 16  1.639371e+06
45    Near Market     Sentra campaign 24  1.574807e+06
46  Future Market      Altima campaign 6  1.554539e+06
47    Near Market      Sentra campaign 8  1.372701e+06
48  Future Market      Altima campaign 5  1.208384e+06
49    Near Market      Sentra campaign 5  1.151432e+06
50    Near Market     Sentra campaign 17  1.066630e+06
51    Near Market     Sentra campaign 13  9.331973e+05
52    Near Market     Sentra campaign 10  8.699296e+05
53  Future Market      Altima campaign 4  3.909630e+05
54  Future Market      Sentra campaign 4  2.001103e+05
55  Future Market      Sentra campaign 2  1.959143e+05
56    Near Market       Kicks campaign 1  1.208160e+05
57    Near Market       Kicks campaign 2  1.492000e+03

4.Does the campaign with maximum impressions also have maximum clicks?

In [192]:
dp=df[df['Metric']=='Clicks']

In [193]:
dp

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0,30,12,2019
5,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Clicks,0.0,30,12,2019
8,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Clicks,0.0,30,12,2019
11,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Clicks,0.0,30,12,2019
14,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Clicks,0.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123686,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Clicks,43.0,30,9,2021
123689,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Clicks,152.0,30,9,2021
123692,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Clicks,102.0,30,9,2021
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.0,30,9,2021
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.0,30,9,2021

In [197]:
db=df[df['Metric']=='Impressions']

In [198]:
db

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.0,30,12,2019
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.0,30,12,2019
12,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Impressions,2.0,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123684,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Impressions,6741.0,30,9,2021
123687,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Impressions,14397.0,30,9,2021
123690,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Impressions,11191.0,30,9,2021
123693,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Impressions,7626.0,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.0,30,9,2021

In [201]:
dp1=dp.groupby(['Campaign','Metric'])['Value'].sum().reset_index()

In [202]:
dp1

                 Campaign  Metric     Value
0       Altima campaign 1  Clicks  148715.0
1       Altima campaign 2  Clicks    2795.0
2       Altima campaign 3  Clicks   13412.0
3       Altima campaign 4  Clicks    3968.0
4       Altima campaign 5  Clicks   13400.0
5       Altima campaign 6  Clicks    7732.0
6       Altima campaign 7  Clicks     672.0
7       Altima campaign 8  Clicks    1790.0
8       Armada campaign 1  Clicks       0.0
9       Armada campaign 2  Clicks  241938.0
10      Armada campaign 3  Clicks   27401.0
11      Armada campaign 4  Clicks   59462.0
12       Kicks campaign 1  Clicks      25.0
13       Kicks campaign 2  Clicks       7.0
14       Kicks campaign 3  Clicks   52065.0
15       Kicks campaign 4  Clicks   25146.0
16       Kicks campaign 5  Clicks   12584.0
17       Kicks campaign 6  Clicks  170446.0
18  Pathfinder campaign 1  Clicks   29140.0
19  Pathfinder campaign 2  Clicks   86662.0
20  Pathfinder campaign 3  Clicks   20326.0
21  Pathfinder campaign 4  Clicks   33544.0
22  Pathfinder campaign 5  Clicks  110696.0
23  Pathfinder campaign 6  Clicks  233938.0
24  Pathfinder campaign 7  Clicks  111136.0
25  Pathfinder campaign 8  Clicks   99810.0
26       Rogue campaign 1  Clicks   68950.0
27       Rogue campaign 2  Clicks   14701.0
28       Rogue campaign 3  Clicks   24951.0
29       Rogue campaign 4  Clicks  209625.0
30       Rogue campaign 5  Clicks  124335.0
31       Rogue pre launch  Clicks   55664.0
32      Sentra campaign 1  Clicks   11357.0
33     Sentra campaign 10  Clicks     411.0
34     Sentra campaign 11  Clicks    3975.0
35     Sentra campaign 12  Clicks    1619.0
36     Sentra campaign 13  Clicks     498.0
37     Sentra campaign 14  Clicks    3501.0
38     Sentra campaign 15  Clicks    1058.0
39     Sentra campaign 16  Clicks     859.0
40     Sentra campaign 17  Clicks     514.0
41     Sentra campaign 18  Clicks    1089.0
42     Sentra campaign 19  Clicks     959.0
43      Sentra campaign 2  Clicks    1626.0
44     Sentra campaign 20  Clicks    1581.0
45     Sentra campaign 21  Clicks    1523.0
46     Sentra campaign 22  Clicks    1502.0
47     Sentra campaign 23  Clicks     952.0
48     Sentra campaign 24  Clicks     839.0
49     Sentra campaign 25  Clicks     864.0
50      Sentra campaign 3  Clicks   25614.0
51      Sentra campaign 4  Clicks    1380.0
52      Sentra campaign 5  Clicks     521.0
53      Sentra campaign 6  Clicks    1412.0
54      Sentra campaign 7  Clicks    1837.0
55      Sentra campaign 8  Clicks     695.0
56      Sentra campaign 9  Clicks    1026.0
57           shop at home  Clicks   16966.0

In [208]:
db1=db.groupby(['Campaign','Metric'])['Value'].sum().reset_index()

In [209]:
db1

                 Campaign       Metric        Value
0       Altima campaign 1  Impressions   35863660.0
1       Altima campaign 2  Impressions    7200627.0
2       Altima campaign 3  Impressions   45451489.0
3       Altima campaign 4  Impressions     380995.0
4       Altima campaign 5  Impressions    1176593.0
5       Altima campaign 6  Impressions    1533773.0
6       Altima campaign 7  Impressions    2043425.0
7       Altima campaign 8  Impressions    6172814.0
8       Armada campaign 1  Impressions    1799471.0
9       Armada campaign 2  Impressions  118817195.0
10      Armada campaign 3  Impressions   17482050.0
11      Armada campaign 4  Impressions   37470993.0
12       Kicks campaign 1  Impressions     120791.0
13       Kicks campaign 2  Impressions       1485.0
14       Kicks campaign 3  Impressions   27167086.0
15       Kicks campaign 4  Impressions   33664998.0
16       Kicks campaign 5  Impressions    1981485.0
17       Kicks campaign 6  Impressions   32993380.0
18  Pathfinder campaign 1  Impressions   48923126.0
19  Pathfinder campaign 2  Impressions  115286607.0
20  Pathfinder campaign 3  Impressions    3977697.0
21  Pathfinder campaign 4  Impressions    5605811.0
22  Pathfinder campaign 5  Impressions   17292561.0
23  Pathfinder campaign 6  Impressions   51823574.0
24  Pathfinder campaign 7  Impressions   16733721.0
25  Pathfinder campaign 8  Impressions   16188937.0
26       Rogue campaign 1  Impressions   18925107.0
27       Rogue campaign 2  Impressions   25647766.0
28       Rogue campaign 3  Impressions    4774134.0
29       Rogue campaign 4  Impressions   32510217.0
30       Rogue campaign 5  Impressions   33448074.0
31       Rogue pre launch  Impressions   16803859.0
32      Sentra campaign 1  Impressions    3119542.0
33     Sentra campaign 10  Impressions     859107.0
34     Sentra campaign 11  Impressions    7803599.0
35     Sentra campaign 12  Impressions    3102923.0
36     Sentra campaign 13  Impressions     922310.0
37     Sentra campaign 14  Impressions    7100167.0
38     Sentra campaign 15  Impressions    2125984.0
39     Sentra campaign 16  Impressions    1619686.0
40     Sentra campaign 17  Impressions    1053431.0
41     Sentra campaign 18  Impressions    2493519.0
42     Sentra campaign 19  Impressions    2005235.0
43      Sentra campaign 2  Impressions     193569.0
44     Sentra campaign 20  Impressions    3076545.0
45     Sentra campaign 21  Impressions    3122121.0
46     Sentra campaign 22  Impressions    2920814.0
47     Sentra campaign 23  Impressions    1870596.0
48     Sentra campaign 24  Impressions    1555632.0
49     Sentra campaign 25  Impressions    1704259.0
50      Sentra campaign 3  Impressions    5512548.0
51      Sentra campaign 4  Impressions     196841.0
52      Sentra campaign 5  Impressions    1137379.0
53      Sentra campaign 6  Impressions    2963379.0
54      Sentra campaign 7  Impressions    3986238.0
55      Sentra campaign 8  Impressions    1356458.0
56      Sentra campaign 9  Impressions    2374129.0
57           shop at home  Impressions    4915930.0

In [210]:
dw=pd.merge(dp1,db1, on='Campaign')

In [211]:
dw

                 Campaign Metric_x   Value_x     Metric_y      Value_y
0       Altima campaign 1   Clicks  148715.0  Impressions   35863660.0
1       Altima campaign 2   Clicks    2795.0  Impressions    7200627.0
2       Altima campaign 3   Clicks   13412.0  Impressions   45451489.0
3       Altima campaign 4   Clicks    3968.0  Impressions     380995.0
4       Altima campaign 5   Clicks   13400.0  Impressions    1176593.0
5       Altima campaign 6   Clicks    7732.0  Impressions    1533773.0
6       Altima campaign 7   Clicks     672.0  Impressions    2043425.0
7       Altima campaign 8   Clicks    1790.0  Impressions    6172814.0
8       Armada campaign 1   Clicks       0.0  Impressions    1799471.0
9       Armada campaign 2   Clicks  241938.0  Impressions  118817195.0
10      Armada campaign 3   Clicks   27401.0  Impressions   17482050.0
11      Armada campaign 4   Clicks   59462.0  Impressions   37470993.0
12       Kicks campaign 1   Clicks      25.0  Impressions     120791.0
13       Kicks campaign 2   Clicks       7.0  Impressions       1485.0
14       Kicks campaign 3   Clicks   52065.0  Impressions   27167086.0
15       Kicks campaign 4   Clicks   25146.0  Impressions   33664998.0
16       Kicks campaign 5   Clicks   12584.0  Impressions    1981485.0
17       Kicks campaign 6   Clicks  170446.0  Impressions   32993380.0
18  Pathfinder campaign 1   Clicks   29140.0  Impressions   48923126.0
19  Pathfinder campaign 2   Clicks   86662.0  Impressions  115286607.0
20  Pathfinder campaign 3   Clicks   20326.0  Impressions    3977697.0
21  Pathfinder campaign 4   Clicks   33544.0  Impressions    5605811.0
22  Pathfinder campaign 5   Clicks  110696.0  Impressions   17292561.0
23  Pathfinder campaign 6   Clicks  233938.0  Impressions   51823574.0
24  Pathfinder campaign 7   Clicks  111136.0  Impressions   16733721.0
25  Pathfinder campaign 8   Clicks   99810.0  Impressions   16188937.0
26       Rogue campaign 1   Clicks   68950.0  Impressions   18925107.0
27       Rogue campaign 2   Clicks   14701.0  Impressions   25647766.0
28       Rogue campaign 3   Clicks   24951.0  Impressions    4774134.0
29       Rogue campaign 4   Clicks  209625.0  Impressions   32510217.0
30       Rogue campaign 5   Clicks  124335.0  Impressions   33448074.0
31       Rogue pre launch   Clicks   55664.0  Impressions   16803859.0
32      Sentra campaign 1   Clicks   11357.0  Impressions    3119542.0
33     Sentra campaign 10   Clicks     411.0  Impressions     859107.0
34     Sentra campaign 11   Clicks    3975.0  Impressions    7803599.0
35     Sentra campaign 12   Clicks    1619.0  Impressions    3102923.0
36     Sentra campaign 13   Clicks     498.0  Impressions     922310.0
37     Sentra campaign 14   Clicks    3501.0  Impressions    7100167.0
38     Sentra campaign 15   Clicks    1058.0  Impressions    2125984.0
39     Sentra campaign 16   Clicks     859.0  Impressions    1619686.0
40     Sentra campaign 17   Clicks     514.0  Impressions    1053431.0
41     Sentra campaign 18   Clicks    1089.0  Impressions    2493519.0
42     Sentra campaign 19   Clicks     959.0  Impressions    2005235.0
43      Sentra campaign 2   Clicks    1626.0  Impressions     193569.0
44     Sentra campaign 20   Clicks    1581.0  Impressions    3076545.0
45     Sentra campaign 21   Clicks    1523.0  Impressions    3122121.0
46     Sentra campaign 22   Clicks    1502.0  Impressions    2920814.0
47     Sentra campaign 23   Clicks     952.0  Impressions    1870596.0
48     Sentra campaign 24   Clicks     839.0  Impressions    1555632.0
49     Sentra campaign 25   Clicks     864.0  Impressions    1704259.0
50      Sentra campaign 3   Clicks   25614.0  Impressions    5512548.0
51      Sentra campaign 4   Clicks    1380.0  Impressions     196841.0
52      Sentra campaign 5   Clicks     521.0  Impressions    1137379.0
53      Sentra campaign 6   Clicks    1412.0  Impressions    2963379.0
54      Sentra campaign 7   Clicks    1837.0  Impressions    3986238.0
55      Sentra campaign 8   Clicks     695.0  Impressions    1356458.0
56      Sentra campaign 9   Clicks    1026.0  Impressions    2374129.0
57           shop at home   Clicks   16966.0  Impressions    4915930.0

In [214]:
dw.max()

Campaign    shop at home
Metric_x          Clicks
Value_x         241938.0
Metric_y     Impressions
Value_y      118817195.0
dtype: object

5.	Find out the top 3 campaigns in terms of CPM (CPM stands for cost per mile which means cost per 1000 impressions. CPM = total media cost/total impressions * 1000)

In [226]:
df_m

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [168]:
df_m.head()

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.0,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.0,30,12,2019,Near Market,Kicks

In [236]:
df_m.tail()

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [169]:
df_imp.groupby(['Campaign','Metric'])['Value'].sum()

Campaign               Metric
Altima campaign 1      Impressions     35863660.0
Altima campaign 2      Impressions      7200627.0
Altima campaign 3      Impressions     45451489.0
Altima campaign 4      Impressions       380995.0
Altima campaign 5      Impressions      1176593.0
Altima campaign 6      Impressions      1533773.0
Altima campaign 7      Impressions      2043425.0
Altima campaign 8      Impressions      6172814.0
Armada campaign 1      Impressions      1799471.0
Armada campaign 2      Impressions    118817195.0
Armada campaign 3      Impressions     17482050.0
Armada campaign 4      Impressions     37470993.0
Kicks campaign 1       Impressions       120791.0
Kicks campaign 2       Impressions         1485.0
Kicks campaign 3       Impressions     27167086.0
Kicks campaign 4       Impressions     33664998.0
Kicks campaign 5       Impressions      1981485.0
Kicks campaign 6       Impressions     32993380.0
Pathfinder campaign 1  Impressions     48923126.0
Pathfinder campaign 2  Impressions    115286607.0
Pathfinder campaign 3  Impressions      3977697.0
Pathfinder campaign 4  Impressions      5605811.0
Pathfinder campaign 5  Impressions     17292561.0
Pathfinder campaign 6  Impressions     51823574.0
Pathfinder campaign 7  Impressions     16733721.0
Pathfinder campaign 8  Impressions     16188937.0
Rogue campaign 1       Impressions     18925107.0
Rogue campaign 2       Impressions     25647766.0
Rogue campaign 3       Impressions      4774134.0
Rogue campaign 4       Impressions     32510217.0
Rogue campaign 5       Impressions     33448074.0
Rogue pre launch       Impressions     16803859.0
Sentra campaign 1      Impressions      3119542.0
Sentra campaign 10     Impressions       859107.0
Sentra campaign 11     Impressions      7803599.0
Sentra campaign 12     Impressions      3102923.0
Sentra campaign 13     Impressions       922310.0
Sentra campaign 14     Impressions      7100167.0
Sentra campaign 15     Impressions      2125984.0
Sentra campaign 16     Impressions      1619686.0
Sentra campaign 17     Impressions      1053431.0
Sentra campaign 18     Impressions      2493519.0
Sentra campaign 19     Impressions      2005235.0
Sentra campaign 2      Impressions       193569.0
Sentra campaign 20     Impressions      3076545.0
Sentra campaign 21     Impressions      3122121.0
Sentra campaign 22     Impressions      2920814.0
Sentra campaign 23     Impressions      1870596.0
Sentra campaign 24     Impressions      1555632.0
Sentra campaign 25     Impressions      1704259.0
Sentra campaign 3      Impressions      5512548.0
Sentra campaign 4      Impressions       196841.0
Sentra campaign 5      Impressions      1137379.0
Sentra campaign 6      Impressions      2963379.0
Sentra campaign 7      Impressions      3986238.0
Sentra campaign 8      Impressions      1356458.0
Sentra campaign 9      Impressions      2374129.0
shop at home           Impressions      4915930.0
Name: Value, dtype: float64

In [171]:
df

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123695,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021
123696,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021
123698,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021

In [172]:
df3=df[df['Metric']=='Media Cost']

In [173]:
df3

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019
7,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Media Cost,0.00,30,12,2019
10,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Media Cost,0.00,30,12,2019
13,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Media Cost,0.00,30,12,2019
...,...,...,...,...,...,...,...,...,...,...
123685,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Media Cost,118.30,30,9,2021
123688,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Media Cost,256.85,30,9,2021
123691,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Media Cost,201.02,30,9,2021
123694,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021
123697,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021

In [175]:
df3.groupby(['Campaign','Metric'])['Value'].sum()

Campaign               Metric
Altima campaign 1      Media Cost    489477.29
Altima campaign 2      Media Cost     74693.85
Altima campaign 3      Media Cost    376369.35
Altima campaign 4      Media Cost      6000.05
Altima campaign 5      Media Cost     18391.45
Altima campaign 6      Media Cost     13033.96
Altima campaign 7      Media Cost     19614.55
Altima campaign 8      Media Cost     47398.70
Armada campaign 1      Media Cost      8210.77
Armada campaign 2      Media Cost    698093.58
Armada campaign 3      Media Cost    145040.71
Armada campaign 4      Media Cost    298919.40
Kicks campaign 1       Media Cost         0.00
Kicks campaign 2       Media Cost         0.00
Kicks campaign 3       Media Cost    181003.85
Kicks campaign 4       Media Cost    181523.37
Kicks campaign 5       Media Cost     28367.02
Kicks campaign 6       Media Cost    370962.96
Pathfinder campaign 1  Media Cost    261944.37
Pathfinder campaign 2  Media Cost    689604.29
Pathfinder campaign 3  Media Cost     73584.37
Pathfinder campaign 4  Media Cost     48319.02
Pathfinder campaign 5  Media Cost    316442.90
Pathfinder campaign 6  Media Cost    797639.63
Pathfinder campaign 7  Media Cost    304427.70
Pathfinder campaign 8  Media Cost    292833.90
Rogue campaign 1       Media Cost    218075.42
Rogue campaign 2       Media Cost    244984.76
Rogue campaign 3       Media Cost     26924.74
Rogue campaign 4       Media Cost    484928.76
Rogue campaign 5       Media Cost    224408.94
Rogue pre launch       Media Cost    150000.03
Sentra campaign 1      Media Cost     13630.70
Sentra campaign 10     Media Cost     10411.61
Sentra campaign 11     Media Cost     91388.52
Sentra campaign 12     Media Cost     36425.55
Sentra campaign 13     Media Cost     10389.33
Sentra campaign 14     Media Cost     82237.26
Sentra campaign 15     Media Cost     24804.88
Sentra campaign 16     Media Cost     18825.91
Sentra campaign 17     Media Cost     12684.74
Sentra campaign 18     Media Cost     30050.35
Sentra campaign 19     Media Cost     23108.76
Sentra campaign 2      Media Cost       719.29
Sentra campaign 20     Media Cost     33861.55
Sentra campaign 21     Media Cost     35633.19
Sentra campaign 22     Media Cost     32146.12
Sentra campaign 23     Media Cost     22497.44
Sentra campaign 24     Media Cost     18335.60
Sentra campaign 25     Media Cost     20103.59
Sentra campaign 3      Media Cost     54522.30
Sentra campaign 4      Media Cost      1889.31
Sentra campaign 5      Media Cost     13532.28
Sentra campaign 6      Media Cost     34295.78
Sentra campaign 7      Media Cost     46075.07
Sentra campaign 8      Media Cost     15547.71
Sentra campaign 9      Media Cost     28385.29
shop at home           Media Cost     51877.36
Name: Value, dtype: float64

In [176]:
df5=df_imp.groupby(['Campaign','Metric'])['Value'].sum().reset_index()

In [177]:
df3=df[df['Metric']=='Media Cost']

In [181]:
df5

                 Campaign       Metric        Value
0       Altima campaign 1  Impressions   35863660.0
1       Altima campaign 2  Impressions    7200627.0
2       Altima campaign 3  Impressions   45451489.0
3       Altima campaign 4  Impressions     380995.0
4       Altima campaign 5  Impressions    1176593.0
5       Altima campaign 6  Impressions    1533773.0
6       Altima campaign 7  Impressions    2043425.0
7       Altima campaign 8  Impressions    6172814.0
8       Armada campaign 1  Impressions    1799471.0
9       Armada campaign 2  Impressions  118817195.0
10      Armada campaign 3  Impressions   17482050.0
11      Armada campaign 4  Impressions   37470993.0
12       Kicks campaign 1  Impressions     120791.0
13       Kicks campaign 2  Impressions       1485.0
14       Kicks campaign 3  Impressions   27167086.0
15       Kicks campaign 4  Impressions   33664998.0
16       Kicks campaign 5  Impressions    1981485.0
17       Kicks campaign 6  Impressions   32993380.0
18  Pathfinder campaign 1  Impressions   48923126.0
19  Pathfinder campaign 2  Impressions  115286607.0
20  Pathfinder campaign 3  Impressions    3977697.0
21  Pathfinder campaign 4  Impressions    5605811.0
22  Pathfinder campaign 5  Impressions   17292561.0
23  Pathfinder campaign 6  Impressions   51823574.0
24  Pathfinder campaign 7  Impressions   16733721.0
25  Pathfinder campaign 8  Impressions   16188937.0
26       Rogue campaign 1  Impressions   18925107.0
27       Rogue campaign 2  Impressions   25647766.0
28       Rogue campaign 3  Impressions    4774134.0
29       Rogue campaign 4  Impressions   32510217.0
30       Rogue campaign 5  Impressions   33448074.0
31       Rogue pre launch  Impressions   16803859.0
32      Sentra campaign 1  Impressions    3119542.0
33     Sentra campaign 10  Impressions     859107.0
34     Sentra campaign 11  Impressions    7803599.0
35     Sentra campaign 12  Impressions    3102923.0
36     Sentra campaign 13  Impressions     922310.0
37     Sentra campaign 14  Impressions    7100167.0
38     Sentra campaign 15  Impressions    2125984.0
39     Sentra campaign 16  Impressions    1619686.0
40     Sentra campaign 17  Impressions    1053431.0
41     Sentra campaign 18  Impressions    2493519.0
42     Sentra campaign 19  Impressions    2005235.0
43      Sentra campaign 2  Impressions     193569.0
44     Sentra campaign 20  Impressions    3076545.0
45     Sentra campaign 21  Impressions    3122121.0
46     Sentra campaign 22  Impressions    2920814.0
47     Sentra campaign 23  Impressions    1870596.0
48     Sentra campaign 24  Impressions    1555632.0
49     Sentra campaign 25  Impressions    1704259.0
50      Sentra campaign 3  Impressions    5512548.0
51      Sentra campaign 4  Impressions     196841.0
52      Sentra campaign 5  Impressions    1137379.0
53      Sentra campaign 6  Impressions    2963379.0
54      Sentra campaign 7  Impressions    3986238.0
55      Sentra campaign 8  Impressions    1356458.0
56      Sentra campaign 9  Impressions    2374129.0
57           shop at home  Impressions    4915930.0

In [179]:
df6=df3.groupby(['Campaign','Metric'])['Value'].sum().reset_index()

In [180]:
df6

                 Campaign      Metric      Value
0       Altima campaign 1  Media Cost  489477.29
1       Altima campaign 2  Media Cost   74693.85
2       Altima campaign 3  Media Cost  376369.35
3       Altima campaign 4  Media Cost    6000.05
4       Altima campaign 5  Media Cost   18391.45
5       Altima campaign 6  Media Cost   13033.96
6       Altima campaign 7  Media Cost   19614.55
7       Altima campaign 8  Media Cost   47398.70
8       Armada campaign 1  Media Cost    8210.77
9       Armada campaign 2  Media Cost  698093.58
10      Armada campaign 3  Media Cost  145040.71
11      Armada campaign 4  Media Cost  298919.40
12       Kicks campaign 1  Media Cost       0.00
13       Kicks campaign 2  Media Cost       0.00
14       Kicks campaign 3  Media Cost  181003.85
15       Kicks campaign 4  Media Cost  181523.37
16       Kicks campaign 5  Media Cost   28367.02
17       Kicks campaign 6  Media Cost  370962.96
18  Pathfinder campaign 1  Media Cost  261944.37
19  Pathfinder campaign 2  Media Cost  689604.29
20  Pathfinder campaign 3  Media Cost   73584.37
21  Pathfinder campaign 4  Media Cost   48319.02
22  Pathfinder campaign 5  Media Cost  316442.90
23  Pathfinder campaign 6  Media Cost  797639.63
24  Pathfinder campaign 7  Media Cost  304427.70
25  Pathfinder campaign 8  Media Cost  292833.90
26       Rogue campaign 1  Media Cost  218075.42
27       Rogue campaign 2  Media Cost  244984.76
28       Rogue campaign 3  Media Cost   26924.74
29       Rogue campaign 4  Media Cost  484928.76
30       Rogue campaign 5  Media Cost  224408.94
31       Rogue pre launch  Media Cost  150000.03
32      Sentra campaign 1  Media Cost   13630.70
33     Sentra campaign 10  Media Cost   10411.61
34     Sentra campaign 11  Media Cost   91388.52
35     Sentra campaign 12  Media Cost   36425.55
36     Sentra campaign 13  Media Cost   10389.33
37     Sentra campaign 14  Media Cost   82237.26
38     Sentra campaign 15  Media Cost   24804.88
39     Sentra campaign 16  Media Cost   18825.91
40     Sentra campaign 17  Media Cost   12684.74
41     Sentra campaign 18  Media Cost   30050.35
42     Sentra campaign 19  Media Cost   23108.76
43      Sentra campaign 2  Media Cost     719.29
44     Sentra campaign 20  Media Cost   33861.55
45     Sentra campaign 21  Media Cost   35633.19
46     Sentra campaign 22  Media Cost   32146.12
47     Sentra campaign 23  Media Cost   22497.44
48     Sentra campaign 24  Media Cost   18335.60
49     Sentra campaign 25  Media Cost   20103.59
50      Sentra campaign 3  Media Cost   54522.30
51      Sentra campaign 4  Media Cost    1889.31
52      Sentra campaign 5  Media Cost   13532.28
53      Sentra campaign 6  Media Cost   34295.78
54      Sentra campaign 7  Media Cost   46075.07
55      Sentra campaign 8  Media Cost   15547.71
56      Sentra campaign 9  Media Cost   28385.29
57           shop at home  Media Cost   51877.36

In [182]:
df5.head()

            Campaign       Metric       Value
0  Altima campaign 1  Impressions  35863660.0
1  Altima campaign 2  Impressions   7200627.0
2  Altima campaign 3  Impressions  45451489.0
3  Altima campaign 4  Impressions    380995.0
4  Altima campaign 5  Impressions   1176593.0

In [183]:
df6.head()

            Campaign      Metric      Value
0  Altima campaign 1  Media Cost  489477.29
1  Altima campaign 2  Media Cost   74693.85
2  Altima campaign 3  Media Cost  376369.35
3  Altima campaign 4  Media Cost    6000.05
4  Altima campaign 5  Media Cost   18391.45

In [184]:
df_p=pd.merge(df5,df6,on='Campaign')

In [185]:
df_p

                 Campaign     Metric_x      Value_x    Metric_y    Value_y
0       Altima campaign 1  Impressions   35863660.0  Media Cost  489477.29
1       Altima campaign 2  Impressions    7200627.0  Media Cost   74693.85
2       Altima campaign 3  Impressions   45451489.0  Media Cost  376369.35
3       Altima campaign 4  Impressions     380995.0  Media Cost    6000.05
4       Altima campaign 5  Impressions    1176593.0  Media Cost   18391.45
5       Altima campaign 6  Impressions    1533773.0  Media Cost   13033.96
6       Altima campaign 7  Impressions    2043425.0  Media Cost   19614.55
7       Altima campaign 8  Impressions    6172814.0  Media Cost   47398.70
8       Armada campaign 1  Impressions    1799471.0  Media Cost    8210.77
9       Armada campaign 2  Impressions  118817195.0  Media Cost  698093.58
10      Armada campaign 3  Impressions   17482050.0  Media Cost  145040.71
11      Armada campaign 4  Impressions   37470993.0  Media Cost  298919.40
12       Kicks campaign 1  Impressions     120791.0  Media Cost       0.00
13       Kicks campaign 2  Impressions       1485.0  Media Cost       0.00
14       Kicks campaign 3  Impressions   27167086.0  Media Cost  181003.85
15       Kicks campaign 4  Impressions   33664998.0  Media Cost  181523.37
16       Kicks campaign 5  Impressions    1981485.0  Media Cost   28367.02
17       Kicks campaign 6  Impressions   32993380.0  Media Cost  370962.96
18  Pathfinder campaign 1  Impressions   48923126.0  Media Cost  261944.37
19  Pathfinder campaign 2  Impressions  115286607.0  Media Cost  689604.29
20  Pathfinder campaign 3  Impressions    3977697.0  Media Cost   73584.37
21  Pathfinder campaign 4  Impressions    5605811.0  Media Cost   48319.02
22  Pathfinder campaign 5  Impressions   17292561.0  Media Cost  316442.90
23  Pathfinder campaign 6  Impressions   51823574.0  Media Cost  797639.63
24  Pathfinder campaign 7  Impressions   16733721.0  Media Cost  304427.70
25  Pathfinder campaign 8  Impressions   16188937.0  Media Cost  292833.90
26       Rogue campaign 1  Impressions   18925107.0  Media Cost  218075.42
27       Rogue campaign 2  Impressions   25647766.0  Media Cost  244984.76
28       Rogue campaign 3  Impressions    4774134.0  Media Cost   26924.74
29       Rogue campaign 4  Impressions   32510217.0  Media Cost  484928.76
30       Rogue campaign 5  Impressions   33448074.0  Media Cost  224408.94
31       Rogue pre launch  Impressions   16803859.0  Media Cost  150000.03
32      Sentra campaign 1  Impressions    3119542.0  Media Cost   13630.70
33     Sentra campaign 10  Impressions     859107.0  Media Cost   10411.61
34     Sentra campaign 11  Impressions    7803599.0  Media Cost   91388.52
35     Sentra campaign 12  Impressions    3102923.0  Media Cost   36425.55
36     Sentra campaign 13  Impressions     922310.0  Media Cost   10389.33
37     Sentra campaign 14  Impressions    7100167.0  Media Cost   82237.26
38     Sentra campaign 15  Impressions    2125984.0  Media Cost   24804.88
39     Sentra campaign 16  Impressions    1619686.0  Media Cost   18825.91
40     Sentra campaign 17  Impressions    1053431.0  Media Cost   12684.74
41     Sentra campaign 18  Impressions    2493519.0  Media Cost   30050.35
42     Sentra campaign 19  Impressions    2005235.0  Media Cost   23108.76
43      Sentra campaign 2  Impressions     193569.0  Media Cost     719.29
44     Sentra campaign 20  Impressions    3076545.0  Media Cost   33861.55
45     Sentra campaign 21  Impressions    3122121.0  Media Cost   35633.19
46     Sentra campaign 22  Impressions    2920814.0  Media Cost   32146.12
47     Sentra campaign 23  Impressions    1870596.0  Media Cost   22497.44
48     Sentra campaign 24  Impressions    1555632.0  Media Cost   18335.60
49     Sentra campaign 25  Impressions    1704259.0  Media Cost   20103.59
50      Sentra campaign 3  Impressions    5512548.0  Media Cost   54522.30
51      Sentra campaign 4  Impressions     196841.0  Media Cost    1889.31
52      Sentra campaign 5  Impressions    1137379.0  Media Cost   13532.28
53      Sentra campaign 6  Impressions    2963379.0  Media Cost   34295.78
54      Sentra campaign 7  Impressions    3986238.0  Media Cost   46075.07
55      Sentra campaign 8  Impressions    1356458.0  Media Cost   15547.71
56      Sentra campaign 9  Impressions    2374129.0  Media Cost   28385.29
57           shop at home  Impressions    4915930.0  Media Cost   51877.36

In [186]:
df_p.head(3)

            Campaign     Metric_x     Value_x    Metric_y    Value_y
0  Altima campaign 1  Impressions  35863660.0  Media Cost  489477.29
1  Altima campaign 2  Impressions   7200627.0  Media Cost   74693.85
2  Altima campaign 3  Impressions  45451489.0  Media Cost  376369.35

In [188]:
df_p['CPM']=(df_p['Value_y']/df_p['Value_x'])*1000

In [189]:
df_p

,Campaign,Metric_x,Value_x,Metric_y,Value_y,CPM
0,Altima campaign 1,Impressions,35863660.0,Media Cost,489477.29,13.648280
1,Altima campaign 2,Impressions,7200627.0,Media Cost,74693.85,10.373242
2,Altima campaign 3,Impressions,45451489.0,Media Cost,376369.35,8.280683
3,Altima campaign 4,Impressions,380995.0,Media Cost,6000.05,15.748369
4,Altima campaign 5,Impressions,1176593.0,Media Cost,18391.45,15.631106
5,Altima campaign 6,Impressions,1533773.0,Media Cost,13033.96,8.497972
6,Altima campaign 7,Impressions,2043425.0,Media Cost,19614.55,9.598860
7,Altima campaign 8,Impressions,6172814.0,Media Cost,47398.70,7.678621
8,Armada campaign 1,Impressions,1799471.0,Media Cost,8210.77,4.562880
9,Armada campaign 2,Impressions,118817195.0,Media Cost,698093.58,5.875358
10,Armada campaign 3,Impressions,17482050.0,Media Cost,145040.71,8.296550
11,Armada campaign 4,Impressions,37470993.0,Media Cost,298919.40,7.977355
12,Kicks campaign 1,Impressions,120791.0,Media Cost,0.00,0.000000
13,Kicks campaign 2,Impressions,1485.0,Media Cost,0.00,0.000000
14,Kicks campaign 3,Impressions,27167086.0,Media Cost,181003.85,6.662616
15,Kicks campaign 4,Impressions,33664998.0,Media Cost,181523.37,5.392051
16,Kicks campaign 5,Impressions,1981485.0,Media Cost,28367.02,14.316041
17,Kicks campaign 6,Impressions,32993380.0,Media Cost,370962.96,11.243557
18,Pathfinder campaign 1,Impressions,48923126.0,Media Cost,261944.37,5.354203
19,Pathfinder campaign 2,Impressions,115286607.0,Media Cost,689604.29,5.981651
20,Pathfinder campaign 3,Impressions,3977697.0,Media Cost,73584.37,18.499240
21,Pathfinder campaign 4,Impressions,5605811.0,Media Cost,48319.02,8.619452
22,Pathfinder campaign 5,Impressions,17292561.0,Media Cost,316442.90,18.299366
23,Pathfinder campaign 6,Impressions,51823574.0,Media Cost,797639.63,15.391444
24,Pathfinder campaign 7,Impressions,16733721.0,Media Cost,304427.70,18.192469
25,Pathfinder campaign 8,Impressions,16188937.0,Media Cost,292833.90,18.088519
26,Rogue campaign 1,Impressions,18925107.0,Media Cost,218075.42,11.523075
27,Rogue campaign 2,Impressions,25647766.0,Media Cost,244984.76,9.551895
28,Rogue campaign 3,Impressions,4774134.0,Media Cost,26924.74,5.639712
29,Rogue campaign 4,Impressions,32510217.0,Media Cost,484928.76,14.916196
30,Rogue campaign 5,Impressions,33448074.0,Media Cost,224408.94,6.709174
31,Rogue pre launch,Impressions,16803859.0,Media Cost,150000.03,8.926523
32,Sentra campaign 1,Impressions,3119542.0,Media Cost,13630.70,4.369456
33,Sentra campaign 10,Impressions,859107.0,Media Cost,10411.61,12.119107
34,Sentra campaign 11,Impressions,7803599.0,Media Cost,91388.52,11.711073
35,Sentra campaign 12,Impressions,3102923.0,Media Cost,36425.55,11.739109
36,Sentra campaign 13,Impressions,922310.0,Media Cost,10389.33,11.264466
37,Sentra campaign 14,Impressions,7100167.0,Media Cost,82237.26,11.582440
38,Sentra campaign 15,Impressions,2125984.0,Media Cost,24804.88,11.667482
39,Sentra campaign 16,Impressions,1619686.0,Media Cost,18825.91,11.623185
40,Sentra campaign 17,Impressions,1053431.0,Media Cost,12684.74,12.041358
41,Sentra campaign 18,Impressions,2493519.0,Media Cost,30050.35,12.051382
42,Sentra campaign 19,Impressions,2005235.0,Media Cost,23108.76,11.524215
43,Sentra campaign 2,Impressions,193569.0,Media Cost,719.29,3.715936
44,Sentra campaign 20,Impressions,3076545.0,Media Cost,33861.55,11.006356
45,Sentra campaign 21,Impressions,3122121.0,Media Cost,35633.19,11.413135
46,Sentra campaign 22,Impressions,2920814.0,Media Cost,32146.12,11.005877
47,Sentra campaign 23,Impressions,1870596.0,Media Cost,22497.44,12.026883
48,Sentra campaign 24,Impressions,1555632.0,Media Cost,18335.60,11.786592
49,Sentra campaign 25,Impressions,1704259.0,Media Cost,20103.59,11.796089
50,Sentra campaign 3,Impressions,5512548.0,Media Cost,54522.30,9.890581
51,Sentra campaign 4,Impressions,196841.0,Media Cost,1889.31,9.598153
52,Sentra campaign 5,Impressions,1137379.0,Media Cost,13532.28,11.897775
53,Sentra campaign 6,Impressions,2963379.0,Media Cost,34295.78,11.573201
54,Sentra campaign 7,Impressions,3986238.0,Media Cost,46075.07,11.558535
55,Sentra campaign 8,Impressions,1356458.0,Media Cost,15547.71,11.461991
56,Sentra campaign 9,Impressions,2374129.0,Media Cost,28385.29,11.956086
57,shop at home,Impressions,4915930.0,Media Cost,51877.36,10.552909

6.	What is the monthly average media cost for different media types?

In [227]:
df_m

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [229]:
df_m1=df_m[df_m['Metric']=='Media Cost']

In [230]:
df_m1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
7,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Media Cost,0.00,30,12,2019,Near Market,Kicks
10,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Media Cost,0.00,30,12,2019,Near Market,Kicks
13,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Indianapolis,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122615,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Milwaukee,Media Cost,118.30,30,9,2021,Near Market,Pathfinder
122618,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Houston,Media Cost,256.85,30,9,2021,Near Market,Pathfinder
122621,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Seattle - Tacoma,Media Cost,201.02,30,9,2021,Near Market,Pathfinder
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder

In [234]:
(df_m1.groupby(['Month','Metric','Year'])['Value'].mean()).reset_index()

    Month      Metric  Year       Value
0       1  Media Cost  2020    0.000000
1       1  Media Cost  2021  119.813492
2       2  Media Cost  2020  421.122630
3       2  Media Cost  2021  151.257794
4       3  Media Cost  2020  302.758842
5       3  Media Cost  2021  174.675495
6       4  Media Cost  2020    0.000000
7       4  Media Cost  2021  124.449810
8       5  Media Cost  2020    0.000000
9       5  Media Cost  2021    0.000000
10      6  Media Cost  2020    6.744024
11      6  Media Cost  2021    0.000000
12      7  Media Cost  2020   24.068340
13      7  Media Cost  2021    0.000000
14      8  Media Cost  2020   63.770189
15      8  Media Cost  2021  242.316774
16      9  Media Cost  2020  477.379175
17      9  Media Cost  2021  267.725076
18     10  Media Cost  2020  240.864445
19     11  Media Cost  2020  123.188914
20     12  Media Cost  2019    0.000000
21     12  Media Cost  2020  217.150739

7.	Which media type is more expensive in terms of CPM?

In [235]:
df_m

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.00,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.00,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.00,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.00,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [240]:
df_m.head()

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.0,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.0,30,12,2019,Near Market,Kicks

In [241]:
df_m.tail()

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [242]:
dk1=df_m[df_m['Media Type']=='Display']

In [243]:
dk1

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
0,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Impressions,1.0,30,12,2019,Near Market,Kicks
1,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Media Cost,0.0,30,12,2019,Near Market,Kicks
2,2019-12-30,Pinterest,Kicks campaign 2,Display,Colorado Springs-Pueblo,Clicks,0.0,30,12,2019,Near Market,Kicks
3,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Impressions,1.0,30,12,2019,Near Market,Kicks
4,2019-12-30,Pinterest,Kicks campaign 2,Display,Sacramnto-Stkton-Modesto,Media Cost,0.0,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
121535,2021-09-27,Pinterest,Sentra campaign 6,Display,"Washington, DC (Hagrstwn)",Media Cost,0.0,27,9,2021,Near Market,Sentra
121536,2021-09-27,Pinterest,Sentra campaign 6,Display,"Washington, DC (Hagrstwn)",Clicks,0.0,27,9,2021,Near Market,Sentra
121543,2021-09-27,Pinterest,Sentra campaign 22,Display,Atlanta,Impressions,1.0,27,9,2021,Near Market,Sentra
121544,2021-09-27,Pinterest,Sentra campaign 22,Display,Atlanta,Media Cost,0.0,27,9,2021,Near Market,Sentra
121545,2021-09-27,Pinterest,Sentra campaign 22,Display,Atlanta,Clicks,0.0,27,9,2021,Near Market,Sentra

In [244]:
dk11=dk1.groupby(['Campaign','Media Type'])['Value'].sum().reset_index()

In [245]:
dk11

                 Campaign Media Type         Value
0       Altima campaign 2    Display  1.870000e+02
1       Altima campaign 3    Display  7.830000e+02
2       Altima campaign 5    Display  2.621000e+01
3       Altima campaign 7    Display  2.160000e+02
4       Altima campaign 8    Display  2.530000e+02
5       Armada campaign 1    Display  1.807682e+06
6       Armada campaign 2    Display  1.197572e+08
7       Armada campaign 3    Display  2.040000e+02
8       Armada campaign 4    Display  2.740000e+02
9        Kicks campaign 1    Display  1.430000e+02
10       Kicks campaign 2    Display  1.492000e+03
11       Kicks campaign 3    Display  2.610000e+02
12       Kicks campaign 4    Display  2.710000e+02
13       Kicks campaign 6    Display  9.000000e+00
14  Pathfinder campaign 1    Display  4.921421e+07
15       Rogue campaign 2    Display  2.720000e+02
16     Sentra campaign 10    Display  1.600000e+01
17     Sentra campaign 12    Display  1.700000e+01
18     Sentra campaign 13    Display  1.200000e+01
19     Sentra campaign 14    Display  1.000000e+00
20     Sentra campaign 15    Display  5.600000e+01
21     Sentra campaign 16    Display  9.000000e+00
22     Sentra campaign 17    Display  5.000000e+00
23     Sentra campaign 18    Display  2.200000e+01
24     Sentra campaign 19    Display  1.100000e+01
25     Sentra campaign 20    Display  9.000000e+00
26     Sentra campaign 21    Display  4.000000e+00
27     Sentra campaign 22    Display  9.000000e+00
28     Sentra campaign 23    Display  3.700000e+01
29     Sentra campaign 24    Display  2.900000e+01
30     Sentra campaign 25    Display  1.000000e+01
31      Sentra campaign 5    Display  1.300000e+01
32      Sentra campaign 6    Display  1.800000e+01
33      Sentra campaign 7    Display  2.000000e+00
34      Sentra campaign 8    Display  2.700000e+01
35      Sentra campaign 9    Display  2.000000e+00
36           shop at home    Display  4.612055e+06

In [246]:
dk2=df_m[df_m['Media Type']=='Online Video']

In [247]:
dk2

,Date,Data source,Campaign,Media Type,City,Metric,Value,Day,Month,Year,Message type,Model
6,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Impressions,2.00,30,12,2019,Near Market,Kicks
7,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Media Cost,0.00,30,12,2019,Near Market,Kicks
8,2019-12-30,Pinterest,Kicks campaign 1,Online Video,New York,Clicks,0.00,30,12,2019,Near Market,Kicks
9,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Impressions,1.00,30,12,2019,Near Market,Kicks
10,2019-12-30,Pinterest,Kicks campaign 1,Online Video,Atlanta,Media Cost,0.00,30,12,2019,Near Market,Kicks
...,...,...,...,...,...,...,...,...,...,...,...,...
122624,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Media Cost,136.94,30,9,2021,Near Market,Pathfinder
122625,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Sacramento - Stockton - Modesto,Clicks,81.00,30,9,2021,Near Market,Pathfinder
122626,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Impressions,16579.00,30,9,2021,Near Market,Pathfinder
122627,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Media Cost,297.78,30,9,2021,Near Market,Pathfinder
122628,2021-09-30,Snapchat,Pathfinder campaign 7,Online Video,Dallas - Ft. Worth,Clicks,128.00,30,9,2021,Near Market,Pathfinder

In [248]:
dk22=dk2.groupby(['Campaign','Media Type'])['Value'].sum().reset_index()

In [249]:
dk22

                 Campaign    Media Type         Value
0       Altima campaign 1  Online Video  3.650185e+07
1       Altima campaign 2  Online Video  7.277929e+06
2       Altima campaign 3  Online Video  4.584049e+07
3       Altima campaign 4  Online Video  3.909630e+05
4       Altima campaign 5  Online Video  1.208358e+06
5       Altima campaign 6  Online Video  1.554539e+06
6       Altima campaign 7  Online Video  2.063496e+06
7       Altima campaign 8  Online Video  6.221750e+06
8       Armada campaign 3  Online Video  1.765429e+07
9       Armada campaign 4  Online Video  3.782910e+07
10       Kicks campaign 1  Online Video  1.206730e+05
11       Kicks campaign 3  Online Video  2.739989e+07
12       Kicks campaign 4  Online Video  3.387140e+07
13       Kicks campaign 5  Online Video  2.022436e+06
14       Kicks campaign 6  Online Video  3.353478e+07
15  Pathfinder campaign 2  Online Video  1.160629e+08
16  Pathfinder campaign 3  Online Video  4.071607e+06
17  Pathfinder campaign 4  Online Video  5.687674e+06
18  Pathfinder campaign 5  Online Video  1.771970e+07
19  Pathfinder campaign 6  Online Video  5.285515e+07
20  Pathfinder campaign 7  Online Video  1.714928e+07
21  Pathfinder campaign 8  Online Video  1.658158e+07
22       Rogue campaign 1  Online Video  1.921213e+07
23       Rogue campaign 2  Online Video  2.590718e+07
24       Rogue campaign 3  Online Video  4.826010e+06
25       Rogue campaign 4  Online Video  3.320477e+07
26       Rogue campaign 5  Online Video  3.379682e+07
27       Rogue pre launch  Online Video  1.700952e+07
28      Sentra campaign 1  Online Video  3.144530e+06
29     Sentra campaign 10  Online Video  8.699136e+05
30     Sentra campaign 11  Online Video  7.898963e+06
31     Sentra campaign 12  Online Video  3.140951e+06
32     Sentra campaign 13  Online Video  9.331853e+05
33     Sentra campaign 14  Online Video  7.185904e+06
34     Sentra campaign 15  Online Video  2.151791e+06
35     Sentra campaign 16  Online Video  1.639362e+06
36     Sentra campaign 17  Online Video  1.066625e+06
37     Sentra campaign 18  Online Video  2.524636e+06
38     Sentra campaign 19  Online Video  2.029292e+06
39      Sentra campaign 2  Online Video  1.959143e+05
40     Sentra campaign 20  Online Video  3.111979e+06
41     Sentra campaign 21  Online Video  3.159273e+06
42     Sentra campaign 22  Online Video  2.954453e+06
43     Sentra campaign 23  Online Video  1.894008e+06
44     Sentra campaign 24  Online Video  1.574778e+06
45     Sentra campaign 25  Online Video  1.725217e+06
46      Sentra campaign 3  Online Video  5.592684e+06
47      Sentra campaign 4  Online Video  2.001103e+05
48      Sentra campaign 5  Online Video  1.151419e+06
49      Sentra campaign 6  Online Video  2.999069e+06
50      Sentra campaign 7  Online Video  4.034148e+06
51      Sentra campaign 8  Online Video  1.372674e+06
52      Sentra campaign 9  Online Video  2.403538e+06
53           shop at home  Online Video  3.727187e+05

In [250]:
dt=pd.merge(dk11,dk22,on='Campaign')

In [251]:
dt

              Campaign Media Type_x     Value_x  Media Type_y      Value_y
0    Altima campaign 2      Display      187.00  Online Video   7277928.85
1    Altima campaign 3      Display      783.00  Online Video  45840487.35
2    Altima campaign 5      Display       26.21  Online Video   1208358.24
3    Altima campaign 7      Display      216.00  Online Video   2063495.55
4    Altima campaign 8      Display      253.00  Online Video   6221749.70
5    Armada campaign 3      Display      204.00  Online Video  17654287.71
6    Armada campaign 4      Display      274.00  Online Video  37829100.40
7     Kicks campaign 1      Display      143.00  Online Video    120673.00
8     Kicks campaign 3      Display      261.00  Online Video  27399893.85
9     Kicks campaign 4      Display      271.00  Online Video  33871396.37
10    Kicks campaign 6      Display        9.00  Online Video  33534779.96
11    Rogue campaign 2      Display      272.00  Online Video  25907179.76
12  Sentra campaign 10      Display       16.00  Online Video    869913.61
13  Sentra campaign 12      Display       17.00  Online Video   3140950.55
14  Sentra campaign 13      Display       12.00  Online Video    933185.33
15  Sentra campaign 14      Display        1.00  Online Video   7185904.26
16  Sentra campaign 15      Display       56.00  Online Video   2151790.88
17  Sentra campaign 16      Display        9.00  Online Video   1639361.91
18  Sentra campaign 17      Display        5.00  Online Video   1066624.74
19  Sentra campaign 18      Display       22.00  Online Video   2524636.35
20  Sentra campaign 19      Display       11.00  Online Video   2029291.76
21  Sentra campaign 20      Display        9.00  Online Video   3111978.55
22  Sentra campaign 21      Display        4.00  Online Video   3159273.19
23  Sentra campaign 22      Display        9.00  Online Video   2954453.12
24  Sentra campaign 23      Display       37.00  Online Video   1894008.44
25  Sentra campaign 24      Display       29.00  Online Video   1574777.60
26  Sentra campaign 25      Display       10.00  Online Video   1725216.59
27   Sentra campaign 5      Display       13.00  Online Video   1151419.28
28   Sentra campaign 6      Display       18.00  Online Video   2999068.78
29   Sentra campaign 7      Display        2.00  Online Video   4034148.07
30   Sentra campaign 8      Display       27.00  Online Video   1372673.71
31   Sentra campaign 9      Display        2.00  Online Video   2403538.29
32        shop at home      Display  4612054.62  Online Video    372718.74

In [252]:
dt['CPM']=(dt['Value_y']/dt['Value_x'])*1000

In [253]:
dt

,Campaign,Media Type_x,Value_x,Media Type_y,Value_y,CPM
0,Altima campaign 2,Display,187.00,Online Video,7277928.85,3.891941e+07
1,Altima campaign 3,Display,783.00,Online Video,45840487.35,5.854468e+07
2,Altima campaign 5,Display,26.21,Online Video,1208358.24,4.610295e+07
3,Altima campaign 7,Display,216.00,Online Video,2063495.55,9.553220e+06
4,Altima campaign 8,Display,253.00,Online Video,6221749.70,2.459190e+07
5,Armada campaign 3,Display,204.00,Online Video,17654287.71,8.654063e+07
6,Armada campaign 4,Display,274.00,Online Video,37829100.40,1.380624e+08
7,Kicks campaign 1,Display,143.00,Online Video,120673.00,8.438671e+05
8,Kicks campaign 3,Display,261.00,Online Video,27399893.85,1.049804e+08
9,Kicks campaign 4,Display,271.00,Online Video,33871396.37,1.249867e+08
10,Kicks campaign 6,Display,9.00,Online Video,33534779.96,3.726087e+09
11,Rogue campaign 2,Display,272.00,Online Video,25907179.76,9.524698e+07
12,Sentra campaign 10,Display,16.00,Online Video,869913.61,5.436960e+07
13,Sentra campaign 12,Display,17.00,Online Video,3140950.55,1.847618e+08
14,Sentra campaign 13,Display,12.00,Online Video,933185.33,7.776544e+07
15,Sentra campaign 14,Display,1.00,Online Video,7185904.26,7.185904e+09
16,Sentra campaign 15,Display,56.00,Online Video,2151790.88,3.842484e+07
17,Sentra campaign 16,Display,9.00,Online Video,1639361.91,1.821513e+08
18,Sentra campaign 17,Display,5.00,Online Video,1066624.74,2.133249e+08
19,Sentra campaign 18,Display,22.00,Online Video,2524636.35,1.147562e+08
20,Sentra campaign 19,Display,11.00,Online Video,2029291.76,1.844811e+08
21,Sentra campaign 20,Display,9.00,Online Video,3111978.55,3.457754e+08
22,Sentra campaign 21,Display,4.00,Online Video,3159273.19,7.898183e+08
23,Sentra campaign 22,Display,9.00,Online Video,2954453.12,3.282726e+08
24,Sentra campaign 23,Display,37.00,Online Video,1894008.44,5.118942e+07
25,Sentra campaign 24,Display,29.00,Online Video,1574777.60,5.430268e+07
26,Sentra campaign 25,Display,10.00,Online Video,1725216.59,1.725217e+08
27,Sentra campaign 5,Display,13.00,Online Video,1151419.28,8.857071e+07
28,Sentra campaign 6,Display,18.00,Online Video,2999068.78,1.666149e+08
29,Sentra campaign 7,Display,2.00,Online Video,4034148.07,2.017074e+09
30,Sentra campaign 8,Display,27.00,Online Video,1372673.71,5.083977e+07
31,Sentra campaign 9,Display,2.00,Online Video,2403538.29,1.201769e+09
32,shop at home,Display,4612054.62,Online Video,372718.74,8.081403e+01